version: '3'

services:
  ponderada:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ponderada
      MYSQL_DATABASE: ponderada
      MYSQL_USER: ponderada
      MYSQL_PASSWORD: ponderada
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
