"""empty message

Revision ID: e62939739350
Revises: ef3dd2421bd5
Create Date: 2024-02-26 11:08:59.194021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e62939739350'
down_revision = 'ef3dd2421bd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('musicas_favoritas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tempo_aproximado', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('data_lancamento', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('musicas_favoritas', schema=None) as batch_op:
        batch_op.drop_column('data_lancamento')
        batch_op.drop_column('tempo_aproximado')

    # ### end Alembic commands ###
